### ISSUE TITLE
'instance.set' creates a new entry in 'instance.data' when the passed variable does not exist

### ISSUE THREAD

**Issue by meyer1994** [kbrsh/moon#199] opened 2018-01-21 19:50 UTC
For example:
```js
const app = new Moon({
  root: '#app',
  data: {
    obj: {
      // this can be accessed via {{obj.text}} and it shows in the DOM
      text: 'some text'
    }
  }
});

// does not change the value of the 'obj.text' and does not update the DOM
app.set('obj.text', 'other text');
```

Instead of `app.set` changing the value of `data.obj.text` it will create an entry `"obj.text"` (with quotes [??]) in the `app.data` object. Using any other value, `app.set('what?            1 2 a false', 1)`, will have the same effect. Using an object, as described [here](https://github.com/kbrsh/moon/issues/134#issuecomment-330734132) works as intended, updating the DOM and setting `app.data.obj.text` to the intended value.
```js
app.set({
  obj: {
    text: 'new text'
  }
});
```

In my opinion, it should throw an error when the desired variable does not match any of the instance.

**Comment by meyer1994** [comment] 2018-01-21 20:18
Apparently this "could" be fixed by changing the `set` method to something like this:
```js
Moon.prototype.set = function(key, value) {
  // Get observer
  const observer = this.observer;
  
  // Moved data variable out of the if/else block
  let data = this.data;

  if(typeof key === "object") {
    // Shallow merge
    for(let prop in key) {
      // Set value
      data[prop] = key[prop];

      // Notify observer of change
      observer.notify(prop);
    }
  } else {
    // Asserting data entry exists
    if(data[key] === undefined) {
      error(`The item "${key}" does not exists in the instance's data`);
      return;
    }

    // Set value
    this.data[key] = value;

    // Notify observer of change
    observer.notify(key);
  }

  // Queue a build
  queueBuild(this);
}
```

**Comment by kbrsh** [comment] 2018-01-22 00:15
Hey! It looks like you're using the v1 development version (on the `master` branch of this repo). I've purposely removed string key paths in favor of the new object notation.

I _can_ add a warning to ensure that the key exists though–I'll keep this open.

**Comment by meyer1994** [comment] 2018-01-22 01:07
Yes. I am using the `master` branch. I am new to this pull request thingy, only used git/github for personal, mostly local, projects. Was I supposed to use some other branch? I am just seeing the `master` and `gh-pages` in my fork.

**Comment by kbrsh** [comment] 2018-01-22 04:11
There's not an issue with your PR or this issue. You just were experiencing expected behavior for v1 (the `master` branch), but were expecting behavior of v0.11.0 (the `v0.11.0` tag or the latest NPM version).

Objects in `set` are in v1 (`master` branch), while key paths in `set` are in v0.11.0 (`v0.11.0` tag). I can still add the warning, but feel free to open a PR for it if you'd like :)

**Comment by kbrsh** [comment] 2018-07-19 01:19
`update` is now used internally to set props, so a warning would not be plausible. Closing for now but am open to discussion.

**Closed by kbrsh** 2018-07-19 01:19 UTC
Labels: feature, help wanted
