### ISSUE TITLE
onCreate() doesn't have access to "this"

### ISSUE THREAD

**Issue by Lomomn** [kbrsh/moon#248] opened 2019-01-30 18:03 UTC
```javascript
<h1>{content}</h1>
<button @click={updateContent($event)}>press me</button>

<script>
export default {
	content: "unchanged",

	onCreate(){
                 // Doesn't work
		 this.update('content', 'pre button pressed')
	},
	
	updateContent(){
		axios.get('/api').then(res => {
                        // Works
			this.update('content', res.data.message);
		});
	}
}
</script>
```

Gives me the error:
```
TypeError: this is undefined[Learn More] css.967bad95.js line 306 > Function:26:7 
```

Did I do something wrong?

**Comment by kbrsh** [comment] 2019-01-31 00:34
It seems to be working [with this reproduction](https://jsfiddle.net/cedhn4st/1/). What version of Moon are you using? Try logging `this` and verifying if it is `undefined`.

**Comment by Lomomn** [comment] 2019-01-31 00:57
Moon v1.0.0-beta.2 too. Here it is in component format https://github.com/Lomomn/WebstackTemplate/tree/master/frontend  

When I add onCreate like in my example above and console.log(this), this===undefined.

**Comment by Lomomn** [comment] 2019-01-31 15:40
Any ideas?

**Comment by Lomomn** [comment] 2019-02-01 15:12
I also tested this with the moon-cli application and I still get the this===undefined error

**Comment by kbrsh** [comment] 2019-02-01 19:39
Looks like a bug. However, I think it has been fixed in 67b32ae39283d7ba6f1b897e8ea9d6c846f52f5f. The way it works using prototypes isn't compatible with the compiler though, but I'm working on it.

I can't think of any workarounds right now, let me know if you find something or have any questions.

**Comment by Lomomn** [comment] 2019-02-01 19:46
Ok, thanks for looking into it. I guess this means I have to fire up Vue again, huh?

**Comment by kbrsh** [comment] 2019-02-01 19:48
Using another library would be good for now as Moon becomes a little more stable. Thanks for the bug report :)

**Comment by Lomomn** [comment] 2019-02-01 19:53
No worries :)

**Comment by Lomomn** [comment] 2019-02-01 19:53
Do you know of any other minimal libraries like Moon?

**Comment by kbrsh** [comment] 2019-02-01 19:59
I don't know of any with a similar API, but check out Preact or Hyperapp. I'd also prefer if you could move this conversation to the Slack and keep GitHub only for discussion on issues :)

**Closed** 2019-05-04 15:13 UTC
Labels: bug
