### ISSUE TITLE
Moon does not compile first component in template

### ISSUE THREAD

**Issue by rizkyramadhan** [kbrsh/moon#183] opened 2017-11-11 09:50 UTC
See this https://jsfiddle.net/qg7pw9cs/

I expected to see this html:
```
<div id="app"><div>Hello</div></div>
```

Current compiled result is:
```
<div id="app"><comp2>Hello</comp2></div>
```

**Comment by rizkyramadhan** [comment] 2017-11-11 09:52
When I change into https://jsfiddle.net/qg7pw9cs/1/

It renders as intended.

**Comment by kbrsh** [comment] 2017-11-11 15:54
That's intended behavior for v1. A component cannot contain another component as it's root element. It will be included in the v1 documentation when released.

**Closed by kbrsh** 2017-11-11 15:54 UTC
