### ISSUE TITLE
The DOM is not rerendered when using custom render function

### ISSUE THREAD

**Issue by mardon86** [kbrsh/moon#185] opened 2017-11-21 08:27 UTC
I'm setting the render function like this
```
var app6 = new Moon({
    el: "#app6",
    data: {
        msg: "Hello World!"
    },
    render: function(m) {
        var self = this;
        var msg = self.get('msg');
        return m('h1', {attrs: {}}, {shouldRender: true}, [m("#text", {shouldRender: true}, msg)]);
    }
});
```
if i set the `msg` like this:
`app6.set('msg', 'Hello Moon!');`
the app6 is not rerendered. Am i doing it wrong ? Thx.

**Comment by kbrsh** [comment] 2017-11-21 18:11
It seems to be working fine for me. I will need a reproduction in a jsFiddle or something similar to see what the problem is.

**Comment by mardon86** [comment] 2017-11-22 15:28
Thank you for the response..

**Comment by kbrsh** [comment] 2017-11-22 16:11
Closing since this has been fixed in v1.

**Closed by kbrsh** 2017-11-22 16:11 UTC
