### ISSUE TITLE
linking of mvl external file

### ISSUE THREAD

**Issue by faststare08** [kbrsh/moon#245] opened 2018-12-31 02:01 UTC
it seems that doesn't support external file with in-browser development because i received an error if I linked it. please kindly fix that. thanks

**Comment by kbrsh** [comment] 2018-12-31 02:17
Can you provide a reproduction or more information?

**Comment by faststare08** [comment] 2018-12-31 06:50
i want the view argument(of new Moon) should be separated as external file instead of swimming in html file.
my suppose file structure is:
-index.html // view
-view.mvl // view
-index.js // model / viewmodel
I tried to separate them in that fashion but I received when I did that.

**Comment by kbrsh** [comment] 2018-12-31 07:39
Separate file views aren't supported. You can write code in your CSS/JS files and use `import` if you want to separate them into different files. The view must always be in a `.mvl` file, not HTML like in your example.

**Comment by faststare08** [comment] 2019-01-01 16:44
can you sight an example?

**Comment by kbrsh** [comment] 2019-01-01 20:43
```html
<h1>{name}</h1>

<script>
    export { default } from './component';
</script>
```

**Comment by faststare08** [comment] 2019-01-22 18:38
its not working if I used moon cdn(in-browser dev only).

**Comment by kbrsh** [comment] 2019-01-23 06:39
MVL files aren't supported with in-browser development, as it requires a separate compiler to create code for the browser. You'll have to use Moon CLI to use MVL, or will have to use other supported in-browser methods for importing files.

**Comment by kbrsh** [comment] 2019-04-28 07:13
Closing because mvl is only supported in a Node environment through Moon CLI.

**Closed by kbrsh** 2019-04-28 07:13 UTC
